---
- name: install packages
  with_items: "{{ nextcloud_packages }}"
  package:
    name: "{{ item.name }}"
  notify:
    - restart php-fpm

- name: configure php-fpm
  template:
    src: php_fpm.j2
    dest: /etc/rc.conf.d/php_fpm
  notify:
    - restart php-fpm

- name: configure fpm pool
  template:
    src: www.conf.j2
    dest: /usr/local/etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm
